export const allItems = [
    {_id: 102, title: 'All Departments'},
    {_id: 103, title: 'Arts & Crafts'},
    {_id: 104, title: 'Automotive'},
    {_id: 105, title: 'Baby'},
    {_id: 106, title: 'Beauty & Personal Care'},
    {_id: 107, title: 'Books'},
    {_id: 108, title: "Boys' Fashion"},
    {_id: 109, title: 'Computers'},
    {_id: 110, title: 'Deals'},
    {_id: 111, title: 'Digital Music'},
    {_id: 112, title: 'Electronics'},
    {_id: 113, title: "Girls' Fashion"},
    {_id: 114, title: 'Health & Household'},
    {_id: 115, title: 'Industrial and Scientific'},
    {_id: 116, title: 'Kindle Store'},
    {_id: 117, title: 'Luggage'},
    {_id: 118, title: "Men's Fashion"},
    {_id: 119, title: 'Movies & TV'},
    {_id: 120, title: 'Music, CDs & Vinyl'},
    {_id: 121, title: 'Pet Supplies'},
    {_id: 122, title: 'Prime Video'},
    {_id: 123, title: 'Software'},
    {_id: 124, title: 'Sports & Outdoors'},
    {_id: 125, title: 'Tools and Home Improvement'},
    {_id: 126, title: 'Toys & Games'},
    {_id: 127, title: 'Video Games'},
    {_id: 128, title: "Women's Fashion"},
    
    
]